package com.royal.crypto.aura7.audit;

import java.util.BitSet;

/**
 * EntropyAuditor: Real-time statistical verification of Aura-7 keystream.
 * Engineered for continuous cryptographic health monitoring.
 */
public class EntropyAuditor {

    private static final double CRITICAL_THRESHOLD = 3.841; // 95% Confidence interval for 1-bit DOF

    /**
     * Performs a Frequency (Monobit) Test.
     * @param keystream The byte array generated by Aura-7.
     * @return true if the keystream passes.
     */
    public boolean verifyKeystream(byte[] keystream) {
        int ones = 0;
        for (byte b : keystream) {
            ones += Integer.bitCount(b & 0xFF);
        }

        int totalBits = keystream.length * 8;
        double n0 = totalBits - ones;
        double n1 = ones;

        // Chi-squared calculation: (n0 - n/2)^2 / (n/2) + (n1 - n/2)^2 / (n/2)
        double statistic = Math.pow(n0 - n1, 2) / totalBits;

        if (statistic > CRITICAL_THRESHOLD) {
            System.err.println("[!] ENTROPY FAILURE: Statistical bias detected in Aura-7 state.");
            return false;
        }
        return true;
    }
}
